Project3-Django/budget_app/urls.py
"""Defines URL patterns for budget_app."""

from django.urls import path
from . import views

app_name = 'budget_app'

urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Page that shows all transaction types
    path('transactions/', views.transactions, name='transactions'),
    #page that shows all transactions for a specific type
    path('transactions/<int:transaction_id>/', views.transaction, name='transaction'),
    #page that shows the form to add a new entry
    path('new_entry/<int:transaction_id>/', views.new_entry, name='new_entry'),
    #page for displaying a bar chart
    path('bar_chart/', views.bar_chart, name='bar_chart'),
]

Project3-Django/budget_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('budget_app.urls')),
]

Project3-Django/budget_app/models.py
from django.db import models

# Create your models here.
class Transaction(models.Model):
    TransactionType = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the model"""
        return str(self.TransactionType)
    
class Entry(models.Model):
    transaction = models.ForeignKey(Transaction, on_delete=models.CASCADE)
    merchant = models.CharField(max_length=200)
    description = models.TextField()
    transaction_amount = models.DecimalField(max_digits=10, decimal_places=2)
    date_added = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name_plural = 'entries'
    
    def __str__(self):
        """Return a string representation of the merchant information"""
        return str(self.merchant)
    

Project3-Django/budget_app/forms.py
from django import forms 

from . models import Entry

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['merchant', 'description', 'transaction_amount']
        labels = {'merchant': "Merchant", 'description': 'Description', 'transaction_amount':'Transaction amount'}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

Project3-Django/budget_app/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

from . models import Transaction
from . forms import EntryForm
import pandas as pd
from bokeh.plotting import figure
from bokeh.embed import components

# Create your views here.
def index(request):
    """The home page for budget_app."""
    return render(request, 'budget_app/index.html')

def transactions(request):
    """Show all transaction types."""
    transactions = Transaction.objects.order_by('date_added')
    context = {'transactions': transactions, 'other_transactions': ['transactions']}
    return render(request, 'budget_app/transactions.html', context)

def transaction(request, transaction_id):
    """Show all transactions for a specific type."""
    transaction = Transaction.objects.get(id=transaction_id)
    entries = transaction.entry_set.order_by('-date_added')
    context = {'transaction': transaction, 'entries': entries}
    return render(request, 'budget_app/transaction.html', context)

def new_entry(request, transaction_id):
    """Add a new entry for a particular transaction type."""
    transaction = Transaction.objects.get(id=transaction_id)
    
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = EntryForm()
    else:
        # POST data submitted; process data.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.transaction = transaction
            new_entry.save()
            return HttpResponseRedirect(reverse('budget_app:transaction', args=[transaction_id]))
    
    context = {'transaction': transaction, 'form': form}
    return render(request, 'budget_app/new_entry.html', context)

def bar_chart(request):
    """Display a bar chart."""
    transactions = Transaction.objects.order_by('date_added')
    transaction_entry_count = [(transaction.id, transaction.entry_set.count()) for transaction in transactions]
    df = pd.DataFrame(transaction_entry_count, columns=['transactions', 'Entry Count'])
    # instantiate a figure object
    fig = figure(x_range=df['Entry Count'], title='Transaction Entry Count', height=500, width=700)
    #create the bar chart
    fig.vbar(source=df, x='Entry Count', top='Transaction', width=0.9, color='purple')
    html, div = components(fig)
    context = {'html': html, 'div': div}
    return render(request, 'budget_app/bar_chart.html', context)

Project3-Django/budget_app/templates/budget_app/bar_chart.html
{% extends "budget_app/base.html" %}
{% block content %}
{{ div | safe}}
<script src="https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js"></script>
{{ html | safe}}
{% endblock content %}

Project3-Django/budget_app/templates/budget_app/base.html
{% load django_bootstrap5 %}
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <title>Budget App</title>
  {% bootstrap_css %}
  {% bootstrap_javascript %}
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-dark mb-4 border" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'budget_app:index'%}">Budget App</a>

          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" 
          data-bs-target="#navbarColor01" aria-controls="navbarColor01" 
          aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          
          <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav me-auto">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'budget_app:transactions'%}">Transactions</a>
              </li>
            </ul>
          </div>
        </div>
    </nav>
    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
        {% block page_header %}{% endblock page_header %}
        </div>
        <div>
          {% block content %}{% endblock content %}
        </div>
    </main>
    
</body>
</html>

Project3-Django/budget_app/templates/budget_app/index.html
{% extends "budget_app/base.html" %}

{% block page_header %}
<section class="bg-light text-center py-5">
    <div class="container">
      <h1 class="display-4">Pythonic Purse</h1>
      <h2>A Pyhton budget application</h2>
      <h3>Intelligent Budgeting, Python-Powered</h3>
    </div>
  </section>
{% endblock page_header %}

{% block content %}

<p>This Budget App will help you achieve the goals you're working toward. 
    Hopefully it will give you an action plan of where your money is going</p>

{% endblock content %}

Project3-Django/budget_app/templates/budget_app/new_entry.html
{% extends 'budget_app/base.html' %}

{% block content %}
   
    <p><a herf="{% url 'budget_app:transaction' transaction.id %}">{{ transaction }}</a></p>

    <p>Add a new entry:</p>
    <form action="{% url 'budget_app:new_entry' transaction.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add entry</button>
    </form>

    {% endblock content %}

Project3-Django/budget_app/templates/budget_app/transaction.html
{% extends 'budget_app/base.html' %}

{% block content %}

<p>Transaction: {{transaction}}</p>

<p>Entries:</p>
<p>
    <a href="{% url 'budget_app:new_entry' transaction.id %}">Add a new entry</a>
</p>
<ul>
{% for entry in entries %}
    <li>
        <p>{{entry.date_added|date:'M d, Y H:i'}}</p>
        <p>{{entry.merchant}}</p>
        <p>{{entry.description|linebreaks}}</p>
        <p>{{entry.transaction_amount}}</p>
    </li>
{% endfor %}
</ul>

{% endblock %}

Project3-Django/budget_app/templates/budget_app/transactions.html
{% extends 'budget_app/base.html' %}

{% block content %}

<p>Transactions</p>
<ul>
    {% for transaction in transactions %}
        <li><a href="{% url 'budget_app:transaction' transaction.id %}">{{ transaction }}</a></li>
    {% endfor %}
</ul>

{% endblock %}