Exercise26/code_journals/urls.py
"""Defines URL patterns for code_journals."""

from django.urls import path

from . import views
app_name = 'code_journals'
urlpatterns = [
    #Home page
    path('', views.index, name='index'),
    # Show all topics.
    path('topics/', views.topics, name='topics'),
    # Detail page for a single topic
    path('topics/<int:topic_id>/', views.topic, name='topic'),
]

Exercise26/code_journals/views.py
from django.shortcuts import render

from . models import Topic

# Create your views here.
def index(request):
    """The home page for code_journals."""
    return render(request, 'code_journals/index.html')

def topics(request):
    """Show all topics."""
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics, 'other_topics': ['other_topics']}
    return render(request, 'code_journals/topics.html', context)

def topic(request, topic_id):
    """Show a single topic and all its entries."""
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'code_journals/topic.html', context)

Exercise26/code_journals/templates/code_journals/topics.html
{% extends "code_journals/base.html" %}

{% block content %}

<p>Topics<p>
    
<ul>
    {% for topic in topics %}
        <li>
            <a href="{% url 'code_journals:topic' topic.id %}">{{ topic }}</a>
        </li>
    {% empty %}
        <li>No topics have been added yet.</li>
    {% endfor %}
</ul>

<ul>
    {% for topic in other_topics %}
        <li>{{ topic }}</li>
    {% empty %}
        <li>No topics have been added yet.</li>
    {% endfor %}
</ul>

{% endblock content %}