Exercise30/code_journal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('code_journals.urls')),
]

Exercise30/code_journals/urls.py
"""Defines URL patterns for code_journals."""

from django.urls import path

from . import views
app_name = 'code_journals'
urlpatterns = [
    #Home page
    path('', views.index, name='index'),
    # Show all topics.
    path('topics/', views.topics, name='topics'),
    # Detail page for a single topic
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    #Page for adding a new topic
	path('new_topic/', views.new_topic, name='new_topic'),
    # Page for adding a new entry
	path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
	# Page for displaying a bar chart
	path('bar_chart/', views.bar_chart, name='bar_chart'),
    # Page for displaying all entries
    path('all_entries/', views.all_entries, name='all_entries'),
]

Exercise30/code_journals/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):
    """A topic the user wants to record info about"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the model"""
        return str(self.text)

class Entry(models.Model):
    """Something specific learned about a topic"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name_plural = 'entries'
        
    def __str__(self):
        """Return a string representation of the model"""
        return str(self.text[:50] + "...")

Exercise30/code_journals/forms.py
from django import forms

from . models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

Exercise30/code_journals/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

from . models import Topic, Entry
from . forms import TopicForm, EntryForm
import pandas as pd
from bokeh.plotting import figure
from bokeh.embed import components

def index(request):
    """The home page for code_journals."""
    return render(request, 'code_journals/index.html')


def topics(request):
    """Show all topics."""
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics, 'other_topics': ['other_topics']}
    return render(request, 'code_journals/topics.html', context)


def topic(request, topic_id):
    """Show a single topic and all its entries."""
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'code_journals/topic.html', context)

def new_topic(request):
    """add a new topic."""
    if request.method != 'POST':
        #No data submitted; create a blank form.
        form = TopicForm()
    else:
        #POST data submitted; process data.
        form = TopicForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('code_journals:topics'))
    
    context = {'form': form}
    return render(request, 'code_journals/new_topic.html', context)

def new_entry(request, topic_id):
    """Add a new entry for a particular topic."""
    topic = Topic.objects.get(id=topic_id)
    
    if request.method != 'POST':
        #No data submitted; create a blank form.
        form = EntryForm()
    else:
        #POST data submitted; process data.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('code_journals:topic', args=[topic_id]))
    
    context = {'topic': topic, 'form': form}
    return render(request, 'code_journals/new_entry.html', context)

def bar_chart(request):
    topics = Topic.objects.all()
    topics_entry_count = [(topic.text, topic.entry_set.count()) for topic in topics]
    df = pd.DataFrame(topics_entry_count, columns=['Topic', 'Entry Count'])
    # Instantiate a figure object
    fig = figure(x_range=df['Topic'], title='Entry Count by Topic', width=700, height=500)
    # Create a bar chart
    fig.vbar(source=df, x='Topic', top='Entry Count', width=0.9, color = "purple")
    html, div = components(fig)
    context = {'html': html, 'div': div}
    return render(request, 'code_journals/bar_chart.html', context)

def all_entries(request):
    "show all entries"
    entries = Entry.objects.order_by('date_added')
    context = {'entries': entries}
    return render(request, 'code_journals/all_entries.html', context)

Exercise30/code_journals/templates/code_journals/all_entries.html
{% extends "code_journals/base.html" %}

{% block page_header %}
    <h2> All Entries </h2>
{% endblock page_header %}

{% block content %}

<table class="table table-hover table-dark">
    <thead>
        <tr>
            <th scope="col">Date</th>
            <th scope="col">Entry</th>
        </tr>
    </thead>
    <tbody>
        {% for entry in entries %}
        <tr class="table-primary">
            <th>{{ entry.date_added|date:'M d, Y H:i' }}</th>
            <td>{{ entry.text|linebreaks }}</td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="3">No entries have been added yet.</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock content %}

Exercise30/code_journals/templates/code_journals/bar_chart.html
{% extends "code_journals/base.html" %}
{% block content %}
{{ div | safe}}
<script src="https://cdn.bokeh.org/bokeh/release/bokeh-3.5.1.min.js"></script>
{{ html | safe}}
{% endblock content %}

Exercise30/code_journals/templates/code_journals/base.html
{% load django_bootstrap5 %}
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <title>Code Journals</title>
  {% bootstrap_css %}
  {% bootstrap_javascript %}
  <link rel="stylesheet" type = "text/css" href="{% static 'bootstrap.css' %}">
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'code_journals:index'%}">Code Journals</a>

          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" 
          data-bs-target="#navbarColor01" aria-controls="navbarColor01" 
          aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          
          <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav me-auto">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'code_journals:topics'%}">Topics</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Other Menu Items</a>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="{% url 'code_journals:new_topic'%}">Add a new topic</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'code_journals:bar_chart'%}">Visuals</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'code_journals:all_entries'%}">All Entries</a>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
        {% block page_header %}{% endblock page_header %}
        </div>
        <div>
          {% block content %}{% endblock content %}
        </div>
    </main>
    
</body>
</html>

Exercise30/code_journals/templates/code_journals/index.html
{% extends "code_journals/base.html" %}

{% block page_header %}
<div class="card text-center bg-light shadow my-5">
    <div class="card-body py-5">
        <h1 class="card-title display-4">Code Journal</h1>
        <p class="card-text lead">A python application</p>
        <hr class="my-4">
        <p>This app contains topics related to CIS 240</p>
    </div>
{% endblock page_header %}

{% block content %}
<h2>Code Journal will help you keep track of your Python 
knowledge for the topics you learn in CIS 240</h2>

{% endblock content %}

Exercise30/code_journals/templates/code_journals/new_entry.html
{% extends "code_journals/base.html" %}

{% block content %}
  <p><a href="{% url 'code_journals:topic' topic.id %}">{{ topic }}</a></p>
  
  <p>Add a new entry:</p>
    <form action="{% url 'code_journals:new_entry' topic.id %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name='submit'>Add entry</button>
    </form>

{% endblock content %}

Exercise30/code_journals/templates/code_journals/new_topic.html
{% extends "code_journals/base.html" %}
{% load django_bootstrap5 %}

{% block page_header %}
    <h2>Add a New Topic:</h2>
{% endblock page_header %}

{% block content %}
    <form action="{% url 'code_journals:new_topic' %}" method='post' class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button "Add Topic" button_type="submit" button_class="btn-primary" %}
    </form>
{% endblock content %}

Exercise30/code_journals/templates/code_journals/topic.html
{% extends 'code_journals/base.html' %}

{% block page_header %}
    <h2>{{ topic }}</h2>
{% endblock page_header %}

{% block content %}

    <p>
        <a href="{% url 'code_journals:new_entry' topic.id %}">add new entry</a>
    </p>
    
{% for entry in entries %}
    <div class="card mb-3"><!-- Open card -->
        <h4 class="card-header">
                {{ entry.date_added|date:'M d, Y H:i' }}
        </h4>
        <div class="card-body">
            {{ entry.text|linebreaks }}
        </div>
    </div><!-- Close card -->
    
{% empty %}
        <p>There are no entries for this topic yet.</p>
{% endfor %}

{% endblock content %}

Exercise30/code_journals/templates/code_journals/topics.html
{% extends "code_journals/base.html" %}

{% block page_header %}
    <h1>Topics</h1>
{% endblock page_header %}

{% block content %}

<ul>
    {% for topic in topics %}
        <li>
            <h3>
                <a href="{% url 'code_journals:topic' topic.id %}">{{ topic }}</a>
            </h3>
        </li>
    {% empty %}
        <li>No topics have been added yet.</li>
    {% endfor %}
</ul>

<h3><a href="{% url 'code_journals:new_topic' %}">Add a New Topic:</a></h3>

{% endblock content %}